[project]
name = "password-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.2",
    "ruff>=0.14.9",
    "segno>=1.6.6",
    "uvicorn>=0.38.0",
]
